"""Writes tests/swing_frames.luau: every frame of the fist and sword M1s, and of the Brawler's kicks, as
part CFrames relative to the HumanoidRootPart (Torso, both arms, the legs for the kicks and the sword's
Handle), for tests/swing.luau to play back.

Usage (from VFX/CombatVFX):  python3 tests/make_swing_fixture.py
"""

import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ANIMS = os.path.join(HERE, "..", "..", "..", "Animations")
sys.path.insert(0, ANIMS)
sys.path.insert(0, os.path.join(ANIMS, "SwordCombo"))
from animkit import to_transform  # noqa: E402
from generate_sword import GRIP, MOTORS, cf, inv  # noqa: E402

sys.path.insert(0, os.path.join(HERE, ".."))
import generate_vfx  # noqa: E402


def joint(name, ch):
    c0, c1 = MOTORS[name]
    pos, rot = to_transform(name, ch)
    return c0 @ cf(pos, rot) @ inv(c1)


def lua_cf(m):
    vals = list(m[:3, 3]) + [m[i, j] for i in range(3) for j in range(3)]
    return "{" + ",".join("%.3f" % v for v in vals) + "}"


def clips(path, sword):
    data = json.load(open(path))
    out = []
    for name, d in data.items():
        if d.get("loop"):  # the idle: nothing to swing
            continue
        ch = d["channels"]

        def at(j, f):
            return ch[j][f] if j in ch else [0.0] * 6

        frames = []
        for f in range(d["frames"] + 1):
            torso = joint("Root", at("Root", f))
            rarm = torso @ joint("RArm", at("RArm", f))
            parts = {"Torso": torso, "Right Arm": rarm, "Left Arm": torso @ joint("LArm", at("LArm", f))}
            if sword:
                pos, rot = to_transform("Handle", at("Handle", f))
                parts["Handle"] = rarm @ GRIP @ cf(pos, rot)
            frames.append("{" + ",".join('["%s"]=%s' % (k, lua_cf(v)) for k, v in parts.items()) + "}")
        out.append('\t\t["%s"] = { hit = %s, frames = {\n\t\t\t%s,\n\t\t} },' % (
            name, d["hit"] if d["hit"] is not None else "nil", ",\n\t\t\t".join(frames)))
    return "\n".join(out)


def kicks():
    """The Brawler's kicks (Abilities/Brawler/anims.py), with the legs."""
    import importlib.util

    path = os.path.join(HERE, "..", "..", "..", "Abilities", "Brawler", "anims.py")
    spec = importlib.util.spec_from_file_location("brawler_anims", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    wanted = {"Brawler Roundhouse": "roundhouse", "Brawler Axe Kick": "axe kick"}
    out = []
    for c, baked in module.bake_all():
        if c.name not in wanted:
            continue
        frames = []
        for f in range(len(baked["Root"])):
            torso = joint("Root", baked["Root"][f])
            parts = {"Torso": torso}
            for j, part in (("RArm", "Right Arm"), ("LArm", "Left Arm"), ("RLeg", "Right Leg"), ("LLeg", "Left Leg")):
                parts[part] = torso @ joint(j, baked[j][f])
            frames.append("{" + ",".join('["%s"]=%s' % (k, lua_cf(v)) for k, v in parts.items()) + "}")
        out.append('\t\t["%s"] = { hit = %d, frames = {\n\t\t\t%s,\n\t\t} },' % (
            wanted[c.name], c.hit, ",\n\t\t\t".join(frames)))
    return "\n".join(out)


def lua_value(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(float(v))
    return '"%s"' % v


def lua_attrs(attrs):
    return "{ " + ", ".join("%s = %s" % (k, lua_value(v)) for k, v in attrs.items()) + " }"


def templates():
    """The swing templates' settings exactly as generate_vfx.py ships them."""
    out = []
    for make in (generate_vfx.sword_swing, generate_vfx.fist_swing, generate_vfx.kick_swing):
        spec = make()
        trails = ", ".join('{ name = "%s", life = %s, attrs = %s }' % (t.name, repr(float(t.life)), lua_attrs(t.attrs))
                           for t in spec["trails"])
        wake = ", ".join('"%s"' % layer.name for layer in spec["layers"]["Wake"])
        out.append('\t\t%s = { attrs = %s, trails = { %s }, wake = { attrs = %s, emitters = { %s } } },' % (
            spec["name"], lua_attrs(spec["attrs"]), trails, lua_attrs(spec.get("wake_attrs", {})), wake))
    return "\n".join(out)


def main():
    sword = clips(os.path.join(ANIMS, "SwordCombo", "sword_data.json"), True)
    fist = clips(os.path.join(ANIMS, "FistCombo", "combo_data.json"), False)
    kick = kicks()
    text = ("-- generated by make_swing_fixture.py: M1 frames as part CFrames relative to the HumanoidRootPart\n"
            "return {\n\ttemplates = {\n%s\n\t},\n\tsword = {\n%s\n\t},\n\tfist = {\n%s\n\t},\n"
            "\tkick = {\n%s\n\t},\n}\n" % (templates(), sword, fist, kick))
    open(os.path.join(HERE, "swing_frames.luau"), "w").write(text)
    print("wrote swing_frames.luau, %d KB" % (len(text) // 1024))


if __name__ == "__main__":
    main()
