"""Builds the Brawler (basic fighting moves: punches, kicks, a slam, grabs and throws) as a drop-in
Roblox kit.

  python3 generate_brawler.py path/to/ANIMSFORCLAUDE.rbxmx path/to/nen.rbxmx

ANIMSFORCLAUDE gives the R6 rig (for the animation rig), nen.rbxmx the sounds. Writes:
  build/Brawler.rbxmx       the ReplicatedStorage folder: Config, GrabPaths, Animations, Sounds, Remote
  build/BrawlerRig.rbxmx    the animation rig (AnimSaves with every clip), for the place
  Brawler.rbxmx             the labelled kit: folders named for where each piece goes
It also checks that the server's timings (Config) land on the animations' Hit markers, and writes
the throws' paths (where the held victim's body goes, frame by frame) into GrabPaths.
"""

import copy
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
SHARED = os.path.join(HERE, "..", "Shared")
sys.path.insert(0, SHARED)
sys.path.insert(0, HERE)
import rbxbuild as B  # noqa: E402
from animkit import FPS, reference_rig  # noqa: E402

SRC = os.path.join(HERE, "src")
VFX = os.path.join(HERE, "..", "..", "VFX", "CombatVFX")
anims = B.load("brawler_anims", os.path.join(HERE, "anims.py"))

ANIMATIONS = {  # the Animation the client loads -> the KeyframeSequence inside it
    "Haymaker": "Brawler Haymaker",
    "Uppercut": "Brawler Uppercut",
    "Roundhouse": "Brawler Roundhouse",
    "AxeKick": "Brawler Axe Kick",
    "Teep": "Brawler Teep",
    "GroundSlam": "Brawler Ground Slam",
    "Grab": "Brawler Grab",
    "Suplex": "Brawler Suplex",
    "Chokeslam": "Brawler Chokeslam",
    "Throw": "Brawler Throw",
    "HeldSuplex": "Brawler Held Suplex",
    "HeldChokeslam": "Brawler Held Chokeslam",
    "HeldThrow": "Brawler Held Throw",
    "GetUp": "Brawler Get Up",
}
SOUNDS = {  # new name: (the game's sound, playback speed, volume) - swap in your own any time
    "Swing": ("Slash", 1.1, 0.55),
    "Punch": ("RockHit", 1.15, 0.9),
    "Heavy": ("RockHit", 0.8, 1.0),
    "Slam": ("GroundHit", 0.95, 1.0),
    "Grab": ("PaperHit", 0.9, 0.7),
}
STRIKES = {"Haymaker": "Brawler Haymaker", "Uppercut": "Brawler Uppercut", "Roundhouse": "Brawler Roundhouse",
           "AxeKick": "Brawler Axe Kick", "Teep": "Brawler Teep", "GroundSlam": "Brawler Ground Slam"}
KEY = {v: k for k, v in ANIMATIONS.items()}


# --------------------------------------------------------------------------- the grab paths
def grab_paths_source(paths):
    """GrabPaths: for each throw, the victim's HumanoidRootPart on every frame, in the grabber's space
    at the grab (his HumanoidRootPart), and when the slam lands and they're let go."""
    lines = [
        "--!strict",
        "-- Generated by generate_brawler.py from anims.py: don't edit, rebuild.",
        "-- Each throw: the held victim's HumanoidRootPart on every frame (Step apart), as CFrame components",
        "-- in the grabber's space at the grab; Hit (the slam lands), Release (they're let go) and Length",
        "-- (the grabber's clip) in seconds; the clips to play (Config.Animations keys); GetUp (they're",
        "-- slammed down and get up after); Toss (the way they fly when let go, for a throw).",
        "return {",
    ]
    for name, p in paths.items():
        frames = []
        for m in p["hrp"][: p["release"] + 1]:
            vals = list(m[:3, 3]) + [m[i, j] for i in range(3) for j in range(3)]
            frames.append("{ " + ", ".join("%.3f" % v for v in vals) + " }")
        release = p["release"]
        hrp = p["hrp"]
        d = hrp[release][:3, 3] - hrp[max(release - 3, 0)][:3, 3]
        d = np.array([d[0], 0.0, d[2]])
        d = d / np.linalg.norm(d) if np.linalg.norm(d) > 1e-6 else np.array([0.0, 0.0, -1.0])
        lines += [
            "\t%s = {" % name,
            '\t\tAttacker = "%s",' % KEY[p["attacker"]],
            '\t\tVictim = "%s",' % KEY[p["victim"]],
            "\t\tGetUp = %s," % ("true" if p["get_up"] else "false"),
            "\t\tHit = %d / 60," % p["hit"],
            "\t\tRelease = %d / 60," % release,
            "\t\tLength = %d / 60," % p["length"],
            "\t\tStep = 1 / 60,",
            "\t\tToss = Vector3.new(%.3f, 0, %.3f)," % (d[0], d[2]),
            "\t\tFrames = {",
        ]
        lines += ["\t\t\t" + f + "," for f in frames]
        lines += ["\t\t},", "\t},"]
    lines.append("}")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- the package
def brawler_folder(nen_rbxmx, game, paths):
    out = B.folder("Brawler", [
        B.module("Config", os.path.join(SRC, "Config.luau")),
        B.source_module("GrabPaths", grab_paths_source(paths)),
        B.animations_folder(ANIMATIONS, game),
        B.sounds_folder(nen_rbxmx, SOUNDS),
        B.item("RemoteEvent", "Remote"),
    ])
    return out


def animation_rig(rig_source, game):
    rig, saves = reference_rig(rig_source, "Brawler Animation Rig")
    for name in ANIMATIONS.values():
        saves.append(copy.deepcopy(game[name]))
    return B.reref(rig)


# --------------------------------------------------------------------------- the server's timings
def check_timings(baked):
    """Every delay the server waits before a hit must land on that animation's Hit marker."""
    config = open(os.path.join(SRC, "Config.luau")).read()
    hits = {c.name: sorted(f for f, m in c.markers.items() if "Hit" in m) for c, _ in baked}
    lengths = {c.name: c.frames for c, _ in baked}
    for key, clip in STRIKES.items():
        block = config[config.index("Config.%s = {" % key):]
        block = block[:block.index("\n}")]
        text = "HitDelay = %d / 60," % hits[clip][0]
        assert text in block, "Config.%s: expected `%s` (the Hit marker in %s)" % (key, text, clip)
    grab = config[config.index("Config.Grab = {"):]
    grab = grab[:grab.index("\n}")]
    assert "At = %d / 60," % hits["Brawler Grab"][0] in grab, "Config.Grab.At = the Hit marker in Brawler Grab"
    assert "GetUp = %d / 60," % lengths["Brawler Get Up"] in grab, "Config.Grab.GetUp = Brawler Get Up's length"
    return hits


# --------------------------------------------------------------------------- the labelled kit
README = """--[[
	BRAWLER (basic fighting moves): where everything goes

	1. The "Brawler" folder                 -> ReplicatedStorage
	2. BrawlerServer (Script)              -> ServerScriptService
	3. BrawlerClient (LocalScript)         -> StarterPlayer > StarterPlayerScripts
	4. CombatVFX (the combat effects pack) -> ReplicatedStorage (skip it if you already have it)
	5. Recommended: the Combat folder -> ReplicatedStorage, CombatServer -> ServerScriptService,
		CombatClient -> StarterPlayerScripts. Every hit then goes through it: F to block, tap F to parry,
		guard breaks and stuns (and grabs beat blocks). Without it the moves still work (plain damage and
		knockback).
	6. Optional: the Loadout folder + LoadoutServer + LoadoutClient, for the ability menu (M) and hotbar.
	7. Optional (Workspace): Brawler Animation Rig - open it in the Animation Editor to publish the
		animations, then paste their ids into Brawler.Config.Animations.

	Play (without the Loadout menu): Z Haymaker, X Uppercut, C Roundhouse, V Axe Kick, E Teep,
	B Ground Slam, T Grab & Throw, G Suplex, H Chokeslam. With it, pick them in the menu (M).
	Everything is tuned in Brawler > Config. The game must use R6 avatars.
	Unpublished animations only play in Studio. Publish them before a live game.
]]
return nil
"""


def labelled_kit(brawler, rig, extras):
    combat, combat_scripts, loadout, loadout_scripts = extras
    kit = B.folder("Brawler (punches, kicks, slams, grabs)", [
        B.source_module("READ ME", README),
        B.folder("1. Put the Brawler folder in ReplicatedStorage", [copy.deepcopy(brawler)]),
        B.folder("2. Put BrawlerServer in ServerScriptService", [
            B.script("Script", "BrawlerServer", os.path.join(SRC, "BrawlerServer.server.luau"))]),
        B.folder("3. Put BrawlerClient in StarterPlayer - StarterPlayerScripts", [
            B.script("LocalScript", "BrawlerClient", os.path.join(SRC, "BrawlerClient.client.luau"))]),
        B.folder("4. Put CombatVFX in ReplicatedStorage", [B.combat_vfx()]),
        B.folder("5. Recommended - the parry system (Combat): folder to ReplicatedStorage, scripts as named",
                 [copy.deepcopy(combat)] + combat_scripts),
        B.folder("6. Optional - the ability menu (Loadout): folder to ReplicatedStorage, scripts as named",
                 [copy.deepcopy(loadout)] + loadout_scripts),
        B.folder("7. Optional - Workspace (animation rig to publish the animations)", [copy.deepcopy(rig)]),
    ])
    return B.reref(kit)


def build(rig_source, nen_rbxmx, extras=None):
    baked = anims.bake_all()
    hits = check_timings(baked)
    paths = {}
    for name, p in anims.GRAB_PATHS.items():
        paths[name] = dict(p, get_up=name != "Throw")
    game = B.sequences(baked)
    brawler = brawler_folder(nen_rbxmx, game, paths)
    rig = animation_rig(rig_source, game)
    os.makedirs(os.path.join(HERE, "build"), exist_ok=True)
    B.write([brawler], os.path.join(HERE, "build", "Brawler.rbxmx"))
    B.write([rig], os.path.join(HERE, "build", "BrawlerRig.rbxmx"))
    open(os.path.join(HERE, "tests", "grab_paths.luau"), "w").write(grab_paths_source(paths))
    if extras:
        B.write([labelled_kit(brawler, rig, extras)], os.path.join(HERE, "Brawler.rbxmx"))
    print("hit markers:", {k: [round(f / FPS, 4) for f in v] for k, v in hits.items() if v})
    print("throws:", {k: (p["hit"], p["release"], p["length"]) for k, p in paths.items()})
    return brawler, rig


if __name__ == "__main__":
    sys.path.insert(0, os.path.join(HERE, "..", "Combat"))
    sys.path.insert(0, os.path.join(HERE, "..", "Loadout"))
    import generate_combat  # noqa: E402
    import generate_loadout  # noqa: E402

    combat = generate_combat.build(sys.argv[2])
    loadout = generate_loadout.build()
    cs = os.path.join(HERE, "..", "Combat", "src")
    ls = os.path.join(HERE, "..", "Loadout", "src")
    extras = (
        combat,
        [B.script("Script", "CombatServer", os.path.join(cs, "CombatServer.server.luau")),
         B.script("LocalScript", "CombatClient", os.path.join(cs, "CombatClient.client.luau"))],
        loadout,
        [B.script("Script", "LoadoutServer", os.path.join(ls, "LoadoutServer.server.luau")),
         B.script("LocalScript", "LoadoutClient", os.path.join(ls, "LoadoutClient.client.luau"))],
    )
    build(sys.argv[1], sys.argv[2], extras)
